### ISSUE TITLE
Not working with Duolingo website 

### ISSUE THREAD

**Issue by JumpRopeCanuck** [calda/DuolingoAudioStories#1]
Sunday, August 23, 2020 - Right now, I'm still getting text in my Stories. Is _**calda**_ working on an update? Please take your time, I'm just really keen on taking my listening comprehension to the next level. All the best!

**Comment by calda** [comment]
Glad you're finding this extension useful! In my experience it doesn't hide the text correctly the first time you load the page, but it _does_ work after you refresh the page. (Not sure why this happens)

Give that a try and let me know if it works!

**Comment by JumpRopeCanuck** [comment]
My Tampermonkey extension shows a **1** in its icon (at the top-right, where my extensions are pinned), so Tampermonkey is reading it and telling me it's active, but refreshing the story just takes me back to the title page (with the Start Story button) - I'm using Chrome.

**Comment by calda** [comment]
You're right, it does seem completely broken right now. I'll take a look when I get a chance -- hopefully it will be an easy fix 🤞🏻

**Comment by calda** [comment]
This is fixed in version 1.2 ([`9058915`](https://github.com/calda/DuolingoAudioStories/commit/9058915039816e5a10cf06c848722d222d6f2e7c))
